### ISSUE TITLE
Security breach open through dependency

### ISSUE THREAD

**Issue by handrus** [natura-cosmeticos/node-base#3]
Our last build got a vulnerability introduced through [mem](https://www.npmjs.com/package/mem) package.

We need to upgrade it to version 4 or higher. This package is a dependency of typeORM, so if the issue is not mapped on their project, let's do it and contribute back.

**Comment by FabricioFFC** [comment]
@handrus we did a pull request to https://github.com/yargs/yargs/pull/1270 (`mem` is not used directly in TypeORM, but it's a `yargs` dependency)
